[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "zero_waste_guide"
authors = [{name = "PASCO Florian", email = "florianpasco@protonmail.com"}]
dynamic = ["version", "description"]
